### ISSUE TITLE
Clear all markup confirmation unclear

### ISSUE THREAD

**Issue by wesdean** [knownasilya/google-maps-markup#34]
The message displayed when clearing all markup is unclear.
google-maps-markup/component.js:26 
`const clearAllConfirm = 'Clearing results will persist the changes, if you want to save a copy of the results please copy the url before clearing the markup.';`

I believe that "will persist" should be "will not persist".
Additionally, in our specific implementation the markup is not saved in the URL, but in a separate place on the site. I believe that a message such as the one below would be more clear and universally applicable.

Perhaps a message such as this would be more clear.
"Markup is unsaved. Do you wish to continue clearing all markup?"

**Comment by knownasilya** [comment]
Published in latest release
